### ISSUE TITLE
Error when there is no "es2015" in project babelrc file

### ISSUE THREAD

**Issue by huchenme** [keyanzhang/identity-obj-proxy#7]
```sh
Couldn't find preset "es2015" relative to directory "/apps/jenkins/build/workspace/XXXX/BUILD/node_modules/identity-obj-proxy"
```

Could you please build to and point main to the dist file instead?

**Comment by keyanzhang** [comment]
The [source file](https://github.com/keyanzhang/identity-obj-proxy/blob/master/src/index.js) is in pure ES5. There's no need to add a compilation step.

The babel compiler is only there for tests: https://github.com/keyanzhang/identity-obj-proxy/commit/f69879b8c5a6e32eb904d74e34b940344ea4e46d
